version: 2
jobs:
  build: 
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
workflows:
  version: 2
  workflow:
    jobs:
      - build
  nightly:
    triggers:
      - schedule:
          cron: "0 * * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build
